ALTER TABLE "Nda"
ADD COLUMN "purpose" TEXT,
ADD COLUMN "budgetMin" DOUBLE PRECISION,
ADD COLUMN "budgetMax" DOUBLE PRECISION,
ADD COLUMN "organizationName" TEXT,
ADD COLUMN "requestedAt" TIMESTAMP(3),
ADD COLUMN "reviewedById" TEXT,
ADD COLUMN "reviewedAt" TIMESTAMP(3),
ADD COLUMN "reviewNote" TEXT;

ALTER TABLE "Nda"
ADD CONSTRAINT "Nda_reviewedById_fkey"
FOREIGN KEY ("reviewedById") REFERENCES "User"("id")
ON DELETE SET NULL
ON UPDATE CASCADE;
